FROM seafileltd/seafile-pro-mc:13.0-latest

ENV \
    SEAFILE_VOLUME=/opt/seafile-data \
    SEAFILE_MYSQL_VOLUME=/opt/seafile-mysql/db \
    SEAFILE_CADDY_VOLUME=/opt/seafile-caddy \
    SEAFILE_ELASTICSEARCH_VOLUME=/opt/seafile-elasticsearch/data \
    TIME_ZONE=America/Toronto
