#!/usr/bin/with-contenv bash

# Check if Tailscale is enabled
if [ "${TAILSCALE_ENABLED}" = "false" ]; then
    echo "Tailscale is disabled. Exiting."
    exit 0
fi

FLAGS=""

# Set the Tailscale authentication key if provided
if ! [ -v TAILSCALE_AUTHKEY ]; then
    echo "WARNING: TAILSCALE_AUTHKEY is not defined. You can set it using the TAILSCALE_AUTHKEY environment variable. Alternatively, you can run `tailscale up` without this variable to be prompted for authentication."
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTHKEY}"
fi

# Set the Tailscale hostname if provided
# Note: This may affect how other Tailscale devices see this device
if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

# Set the Tailscale SSH configuration if provided
if [ -v TAILSCALE_USE_SSH ]; then
    FLAGS="${FLAGS} --ssh=${TAILSCALE_USE_SSH}"
fi

# Accept DNS over Tailscale
if [ -v TAILSCALE_ACCEPT_DNS ]; then
    FLAGS="${FLAGS} --accept-dns=${TAILSCALE_ACCEPT_DNS}"
    if [ "${TAILSCALE_ACCEPT_DNS}" = "true" ]; then
        python3 /opt/code-server-scripts/modify_resolv_conf.py --nameserver 100.100.100.100
    fi
fi

# Configure Tailscale to act as an exit node if requested
# Note: This requires approval in the Tailscale admin console
if [ -v TAILSCALE_BE_EXIT_NODE ]; then
    echo "WARNING: Acting as an exit node. This requires approval in the Tailscale admin console."
    FLAGS="${FLAGS} --advertise-exit-node=${TS_BE_EXIT_NODE}"
fi

# Use a custom login server if provided
if [ -v TAILSCALE_LOGIN_SERVER ]; then
    echo "INFO: Using a custom login server: ${TAILSCALE_LOGIN_SERVER}"
    FLAGS="${FLAGS} --login-server=${TAILSCALE_LOGIN_SERVER}"
fi

tailscale up $FLAGS

# Set the web client preference
if [ -v TAILSCALE_USE_WEBCLIENT ]; then
    tailscale set --webclient=${TAILSCALE_USE_WEBCLIENT}
fi

# Enable auto-update
if [ -v TAILSCALE_AUTO_UPDATE ]; then
    tailscale set --auto-update=${TAILSCALE_AUTO_UPDATE}
fi

# Configure Tailscale to serve or funnel traffic
if [ -v TAILSCALE_SERVE_PORT ] && [ -v TAILSCALE_SERVE_MODE ]; then
    if [ -v TAILSCALE_FUNNEL ]; then
        tailscale funnel --"${TAILSCALE_SERVE_MODE}"=443 http://localhost:"${TAILSCALE_SERVE_PORT}" &
    else
        tailscale serve --"${TAILSCALE_SERVE_MODE}"=443 http://localhost:"${TAILSCALE_SERVE_PORT}" &
    fi
fi