#!/usr/bin/with-contenv bash

# Check if PATCH_JSON is set to a value representing "true"
if [[ -n "$PATCH_JSON" && "${PATCH_JSON,,}" =~ ^(true|yes|1|on|y)$ ]]; then
  echo "Patching settings.json with git.json patches"
  python3 /opt/code-server-scripts/patch_json.py --source /config/data/Machine/settings.json --force --in-place /usr/share/code-server-scripts/*.json
  python3 /opt/code-server-scripts/patch_json.py --source /config/data/User/settings.json --force --in-place /usr/share/code-server-scripts/*.json
fi